### ISSUE TITLE
Z.E.50 Reporting incorrect charging speed

### ISSUE THREAD

**Issue by MattCheetham** [MattCheetham/zeddy-support#1]
Creating this on behalf of the user reports I've already received. But please comment below to continue the investigation.

**Describe the bug**
Charging speed is reported incorrectly, usually much much higher than expected.

**To Reproduce**
1. Put the car on charge
2. Refresh Zeddy
3. Observe incorrect charging speed

**iOS version**: 13.5.1
**Zeddy version**: 2.1 (17)
**iOS device**: iPhone 11 Pro
**Reproducible:** Every time

**Expected behavior**
Zeddy should display the correct charging speed

**Screenshots**
None yet. I cannot replicate this myself

**Additional context**
This is reported on behalf of other users. Please comment below with screenshots of your charging displayed charging speed, what speed charger you are using and please click "Collect logs" from the diagnostics screen and look for the value against `chargingInstantaneousPower` if you are able to.

**Comment by MattCheetham** [comment]
At this time it seems that Renault report an incorrect speed, as the Z.E.22 and Z.E.40 report this value in watt hours of kilowattt hours. Zeddy can only display what it is given but if we can work out a pattern in the value there is a chance we may be able to convert it to a usable value.

**Comment by ik2wxx** [comment]
![IMG_9255](https://user-images.githubusercontent.com/948445/85270382-81350700-b479-11ea-8532-9f227554fce0.png)

**Comment by Dave-09** [comment]
It does indeed continuously go wrong :(no idea why! Works well with the old ZOE.

![WhatsApp Image 2020-06-20 at 21 40 15](https://user-images.githubusercontent.com/49677301/85272353-5ac49b00-b47c-11ea-8472-ff15d64bd6b5.jpeg)

**Comment by Dave-09** [comment]
Hello Matt,

On LINUX I also use a python script with my 'old' ZOE. I searched there, but no one reported a bug there regarding this issue. Now I came across the option 'chargeStartInstantaneousPower'. Does it exist for the new ZOE? perhaps that it gives the correct information?

Please check this one:

https://github.com/jamesremuscat/pyze/issues/17

Thank you!

**Comment by coolio2004** [comment]
![IMG_6765](https://user-images.githubusercontent.com/4072535/85275129-2c48bf00-b480-11ea-84ab-70f927e27602.png)
Logfile tells:
2020-06-21 07:30:36 +0000
{
"data" : {
 "type" : "Car",
 "id" : "VF1AG000xxxxxxxxxxxxx",
 "attributes" : {
   "batteryAvailableEnergy" : 47,
   "chargingInstantaneousPower" : 18.600000000000001,
   "chargingStatus" : 1,
   "batteryTemperature" : 20,
   "batteryAutonomy" : 328,
   "chargingRemainingTime" : 125,
   "plugStatus" : 1,
   "timestamp" : "2020-06-21T07:30:26Z",
   "batteryLevel" : 91,
   "batteryCapacity" : 0

**Comment by MattCheetham** [comment]
@Dave-09 `chargeStartInstantaneousPower` is a value that exists on charge history data, which does not exist for the ZE50 currently. I use `chargingInstantaneousPower` from the battery status endpoint. Can you confirm in these screenshots what kW speed the charger is that the car is connected to? Thanks

**Comment by coolio2004** [comment]
Hi Matt,
i always fix my charger to 16A with 1Phase-that means 3,7 kw. I use my photovoltaik power for charging. So i limited it to 3,7 kw. 
Hope I can help you. Its a pitty that ZE50 has no history.
Hans@coolio2004

Von meinem iPad Pro gesendet

**Comment by Dave-09** [comment]
> @Dave-09 `chargeStartInstantaneousPower` is a value that exists on charge history data, which does not exist for the ZE50 currently. I use `chargingInstantaneousPower` from the battery status endpoint. Can you confirm in these screenshots what kW speed the charger is that the car is connected to? Thanks

Hello Matt,

Charging station is 22 kW.

**Comment by Dave-09** [comment]
Hello Matt,

No idea if this is the problem with the ZE50? can you check that?
Please check this one: https://github.com/jamesremuscat/pyze/pull/59

**Comment by MattCheetham** [comment]
@Dave-09 Zeddy already accommodates for the difference in cars reporting watts and kilowatts. The issue is the ZE50 reporting a completely unknown number in an unknown value.

**Comment by Dave-09** [comment]
@MattCheetham,

Thanks! I'm afraid we won't be able to fix that ourselves if the Renault API continues this way :(

**Comment by ik2wxx** [comment]
Hi, let me add something on this.
First of all I should say that my wife owns a Zoe ZE50 and I'm an app developer.
I did not know how Zeddy access the Zoe data, but now I've found, so I wanted to try the Renault API by myself on my Zoe and this is what I've found.
I can confirm that Renault API do not report correct values on charging power.
And that is not a watt to kw conversion problem.
I have two variable power wallboxes (monophase) and tried various power charging from 2 to 6.5 kw, but API always tells a number near 72 no matter what the power is.
Have to say that the number is not always 72 in the entire process, it starts lower and after 10-20s raises to 72, like it means 'now in full charge powe' (just my thought). 
But 72 does not mean nothing regarding current supplied kw.
Other apps that use OBD to get charging power on ZE50 have similar problems, so right now there is no working solution for current charging power on ZE50.

**Comment by coolio2004** [comment]
What I canˋt understand. Prognostic charging time is correct - so there must be a real value for charging power on renault server.

**Comment by MattCheetham** [comment]
@ik2wxx Thanks for this. Very informative. I didn't know that the issue also affected OBD readings too. Confirms it's definitely a readout issue with the software in the car. Sounds like the car itself would need a firmware update to fix. Yikes!

**Comment by Dave-09** [comment]
There happened to be an update this weekend in the Netherlands. Renault is talking about a 'test' so that they can see whether live updates work via the mobile network. Maybe they have a FIX in this. Incidentally, I also do not exclude that Renault doesn't know about this bug because the My Renault app doesn't provide this information.

**Comment by coolio2004** [comment]
Rollout of new firmware 283C32219R arrived on some cars in germany. But no details what is fixed.

**Comment by ik2wxx** [comment]
> @ik2wxx Thanks for this. Very informative. I didn't know that the issue also affected OBD readings too. Confirms it's definitely a readout issue with the software in the car. Sounds like the car itself would need a firmware update to fix. Yikes!

OBD data is partially encrypted on ZE50 (didn't tried by myself, just have 3 OBD and no-one works well with ZE50).
I also think that Renault does not care about charging power as this data is not displayed in their app (very bad).

**Comment by Dave-09** [comment]
> > @ik2wxx Thanks for this. Very informative. I didn't know that the issue also affected OBD readings too. Confirms it's definitely a readout issue with the software in the car. Sounds like the car itself would need a firmware update to fix. Yikes!
> 
> OBD data is partially encrypted on ZE50 (didn't tried by myself, just have 3 OBD and no-one works well with ZE50).
> I also think that Renault does not care about charging power as this data is not displayed in their app (very bad).

Indeed, I also think Renault doesn't know about the bug. I asked someone (got that update this week) if he can check if it is still wrong. Unfortunately, Zeddy is not yet working due to the Renault API. We have to wait for Apple to release the Zeddy update.

I will keep you posted when he has tested it!

**Comment by ik2wxx** [comment]
> Indeed, I also think Renault doesn't know about the bug. I asked someone (got that update this week) if he can check if it is still wrong. Unfortunately, Zeddy is not yet working due to the Renault API. We have to wait for Apple to release the Zeddy update.
> 
> I will keep you posted when he has tested it!

Tried now on my wife ZE50, but no firmware update available (I have 7" display, someone wrote the update is a test for 10" devices).

**Comment by Dave-09** [comment]
Problem still exists after the firmware update in the car! I asked a friend to report this to Renault.

**Comment by ik2wxx** [comment]
I have a suggestion.
If, as someone else wrote, charge time looks to be correct, as we know charge % and charge time, we can guess charging power.
Anyone interested in this ?
The curve is not linear, as I've tried by myself with my adjustable wallbox.
I can provide charge time for 100% battery from 1.8kw to 6kw (my Zoe was at 25% and I've done the math to compute 100% time).
If someone else has 22kw and 50kw charging times, we can extend the guess.
If anyone interested.

**Comment by bartvriesema** [comment]
I updated the car to the latest version last week (Netherlands) and started using Zeddy two days ago. The charging speed issue is still there. I am connected to a 11 kW charger but saw much higher speeds in Zeddy. 
It seems to be off by a factor 3, but that is just a guess based on feeling. Charging started around 29 kW according to Zeddy and gradually lowered to 18 kW. Which feels like okay if you read it like 10 kW going down to 6 kW.

**Comment by coolio2004** [comment]
This is the charging power from my wallbox and what Zeddy offers:
![IMG_6783](https://user-images.githubusercontent.com/4072535/87056655-3c91c580-c206-11ea-9ce4-07e4d587747c.png)
![IMG_6784](https://user-images.githubusercontent.com/4072535/87056665-3e5b8900-c206-11ea-9b45-ba20c0b15da4.png)

**Comment by ik2wxx** [comment]
With my Zoe, Zeddy always report about 72kW at any power I'm charging, from 1.8kW to 6kW.
It's not a kW/3 rule.
